package com.waleed.app.util

object AppConstants {



    const val BASE_URL = "https://www.waleedtoys.com/api/"
    const val KEY_ENABLE_TOOLBAR = "ENABLE_TOOLBAR"
    const val PREF_KEY_IS_SCREEN_ANIM_UP = "IS_UP"

    /**#### PREFERENCE LANG #####*/
    const val PREF_KEY_SELECTED_LANG = "WALEED_SELECTED_LANG"
    const val PREF_KEY_IS_FIRST_OPEN = "WALEED_FIRST_OPEN"
    const val PREF_KEY_IS_CART_ADDED = "CART_ADDED"
    const val PREF_KEY_CART_COUNT = "CART_COUNT"
    const val PREF_IS_LOGGED_IN = "IS_LOGGED_IN"
    const val KEY_IS_USER_LOGGED_IN = "IS_LOGGED_IN"
    const val PREF_ACCOUNT = "LOGGED_ACCOUNT"
    const val PREF_SAVED_CART_ITEM = "SAVED_CART_ITEM"
    const val PREF_DEVICE_TOKEN = "PREF_DEVICE_TOKEN"
    const val PREF_IS_VIDEO_SHOWN = "IS_VIDEO_SHOWN"
    const val PREF_LOCAL_CART = "PREF_LOCAL_CART"
    const val PREF_GUEST_USER = "PREF_GUEST_USER"
    const val PREF_GUEST_USER_DATA = "PREF_GUEST_USER_DATA"
    const val PREF_GUEST_ADDRESS = "PREF_GUEST_ADDRESS"

    /**__________BUNDLE KEYS_____________*/
    const val KEY_SCREEN_NAME = "SCREEN_TITLE"
    const val KEY_CAT_NAME = "CATEGORY_NAME"
    const val KEY_STORE_NAME = "STORE_NAME"
    const val KEY_STORE_ID = "STORE_ID"
    const val BUNDLE_CART_DATA = "CART_DATA"
    const val BUNDLE_WRAP_URL = "WRAP_URL"
    const val BUNDLE_ADDRESS = "WRAP_URL"

    const val BUNDLE_MAP_AREA = "BUNDLE_MAP_AREA"
    const val BUNDLE_MAP_GOV = "BUNDLE_MAP_GOV"
    const val BUNDLE_MAP_STREET = "BUNDLE_MAP_STREET"
    const val BUNDLE_MAP_DIRECTION = "BUNDLE_MAP_DIRECTION"
    const val BUNDLE_LOGGED_USER_ID = "LOGGED_USER_ID"
    const val BUNDLE_MAP_LATITUDE = "BUNDLE_MAP_LATITUDE"
    const val BUNDLE_MAP_LONGITUDE = "BUNDLE_MAP_LONGITUDE"

    const val BUNDLE_FROM_PAGE = "FROM_PAGE"
    const val BUNDLE_FROM_LOGIN_PAGE = "FROM_LOGIN_PAGE"
    const val BUNDLE_KEY_IDEAL_ID = "KEY_IDEAL_ID"
    const val KEY_CATEGORY_DATA = "KEY_CATEGORY_DATA"
    const val KEY_SUB_CATEGORY_DATA = "KEY_SUB_CATEGORY_DATA"
    const val KEY_CATEGORY_ID = "KEY_CATEGORY_ID"
    const val KEY_PRODUCT_DATA = "KEY_PRODUCT_DATA"
    const val KEY_STORE_LIST = "KEY_STORE_LIST"
    const val KEY_SELECTED_STORE = "KEY_SELECTED_STORE"
    const val KEY_SELECTED_STORE_POSITION = "KEY_SELECTED_STORE_POSITION"
    const val BUNDLE_REVIEW_LIST = "BUNDLE_REVIEW_LIST"
    const val BUNDLE_REVIEW_IMAGE_LIST = "BUNDLE_REVIEW_IMAGE_LIST"
    const val BUNDLE_REVIEW_COUNT = "BUNDLE_REVIEW_COUNT"
    const val BUNDLE_REVIEW_RATING = "BUNDLE_REVIEW_RATING"
    const val BUNDLE_KEY_SELECTED_STORE_DATA = "BUNDLE_KEY_SELECTED_STORE_DATA"
    const val KEY_IS_FROM_SUBCATEGORY = "KEY_IS_FROM_SUBCATEGORY"
    const val BUNDLE_FROM_HOME = "BUNDLE_FROM_HOME"
    const val BUNDLE_ADDRESS_DATA = "BUNDLE_ADDRESS_DATA"
    const val BUNDLE_KEY_ADDRESS_EDIT = "BUNDLE_KEY_ADDRESS_EDIT"
    const val BUNDLE_TOTAL = "BUNDLE_TOTAL"
    const val BUNDLE_SUB_TOTAL = "BUNDLE_SUB_TOTAL"
    const val BUNDLE_SELECTED_ADDRESS = "BUNDLE_SLECTED_ADDRESS_ID"
    const val BUNDLE_PAYMENT_DETAILS = "BUNDLE_PAYMENT_DETAILS"
    const val BUNDLE_TRANSACTION_ID = "BUNDLE_TRANSACTION_ID"
    const val BUNDLE_PAYMENT_STATUS = "BUNDLE_PAYMENT_STATUS"
    const val BUNDLE_ORDER_DETAILS = "BUNDLE_ORDER_DETAILS"
    const val BUNDLE_SEARCH_VALUE = "BUNDLE_SEARCH_VALUE"
    const val BUNDLE_ADDRESS_LIST = "BUNDLE_ADDRESS_LIST"
    const val FILTER_ADDRESS_EMPTY = "FILTER_ADDRESS_EMPTY"
    const val BUNDLE_REVIEW_PRODUCT = "BUNDLE_REVIEW_PRODUCT"
    const val BUNDLE_ORDER_DATE = "BUNDLE_ORDER_DATE"
    const val BUNDLE_ORDER_ID = "BUNDLE_ORDER_ID"
    const val BUNDLE_CART = "BUNDLE_CART"
    const val BUNDLE_ZOOM_URL = "BUNDLE_ZOOM_URL"
    const val BUNDLE_CART_RESPONSE = "BUNDLE_CART_RESPONSE"
    const val BUNDLE_TERMS_PAGE_NUMBER = "BUNDLE_TERMS_PAGE_NUMBER"
    const val KEY_IS_EDIT = "KEY_IS_EDIT"
    const val KEY_CHILD_DATA="KEY_CHILD_DATA"
    const val KEY_BUNDLE_GUEST="KEY_GUEST"
    const val KEY_BUNDLE_IS_GUEST="KEY_BUNDLE_IS_GUEST"
    /**----------RESULT CODES____________*/
    const val ADD_ADDRESS_MAP_REQUEST_CODE = 408
    const val LOGIN_REQUEST_CODE = 305
    const val REGISTER_REQUEST_CODE = 306
    const val SEARCH_CODE = 404
    const val STORE_REQUEST = 505
    const val PAYMENT_REQUEST = 909
    const val ACCOUNT_UPDATE = 111
    const val REQUEST_CODE_CART_FROM_DETAILS=456

    const val ACTION_BROADCAST_CART_COUNT = "ACTION_BROADCAST_CART_COUNT"
}